name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {
            os: windows-2019,
            name: windows
          }
        version:
        #- name: v3.3.3996
        #  patch-file: ../.github/workflows/3.5_0001-Support-building-plugins-without-an-install.patch
        #- name: v3.4.4271-stable
        #  patch-file: ../.github/workflows/3.5_0001-Support-building-plugins-without-an-install.patch
        #- name: v3.5.4526-stable
        #  patch-file: ../.github/workflows/3.5_0001-Support-building-plugins-without-an-install.patch
        #- name: v4.0.4958-stable
        #  patch-file: ../.github/workflows/4.0_0001-Support-building-plugins-without-an-install.patch
        - name: v4.1.5747-stable
          patch-file: ../.github/workflows/4.1_0001-Support-building-plugins-without-an-install.patch
        - name: dev
          patch-file: ../.github/workflows/4.1_0001-Support-building-plugins-without-an-install.patch
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Update submodule
      run: |
        git clone --recurse-submodules https://github.com/Vector35/binaryninja-api binaryninjaapi
        cd binaryninjaapi
        git fetch --tags
        git checkout --force ${{matrix.version.name}}
        git submodule update --init --recursive
    - name: Patch api to allow building headlessly
      shell: bash
      run: |
        cd binaryninjaapi
        git apply --verbose ${{matrix.version.patch-file}}
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload artifact for Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.name}}-${{matrix.version.name}}
        path: ${{github.workspace}}/build/*sigscan*
    - name: Upload artifact for macOS
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.name}}-${{matrix.version.name}}
        path: ${{github.workspace}}/build/out/bin/*sigscan*
    - name: Upload artifact for Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.name}}-${{matrix.version.name}}
        path: ${{github.workspace}}/build/out/bin/*sigscan*
